### ISSUE TITLE
Alternating row colours in KeePassXC

### ISSUE THREAD

**Issue by jurf** [FedoraQt/adwaita-qt#103]
![obrazok](https://user-images.githubusercontent.com/7472425/40442140-2945f512-5ec3-11e8-8583-5d607bcffc3c.png)

(Not showing the other side for obvious reasons.)

KeePassXC is available on [Flathub](https://flathub.org/apps/details/org.keepassxc.KeePassXC) if you wanna try.

If not obvious, it’s been a long time since Adwaita GTK+ has dropped alternating row colours. See e.g. System Monitor.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/adwaita-qt/releases/tag/1.0.90.

**Comment by jurf** [comment]
I still get _slightly_ alternating row colours. Is that intentional?

![obrázok](https://user-images.githubusercontent.com/7472425/60575524-fcd70900-9d7b-11e9-8216-0dfddf827499.png)

**Comment by grulja** [comment]
> I still get _slightly_ alternating row colours. Is that intentional?
> 
> ![obrázok](https://user-images.githubusercontent.com/7472425/60575524-fcd70900-9d7b-11e9-8216-0dfddf827499.png)

No, that's not intentional, I'll try to fix that.

**Comment by grulja** [comment]
Should be fixed now with https://github.com/FedoraQt/adwaita-qt/commit/b6df5511cc1555c7b0cfe01557a0f580bfab1d4d.
