### ISSUE TITLE
UI components of a Qt app have larger paddings compared to GTK apps

### ISSUE THREAD

**Issue by jayesh-bhoot** [FedoraQt/adwaita-qt#104]
This is best demonstrated by the _transmission-gtk_ and _transmission-qt_ apps. As an example, I have attached 2 screenshots showing the large paddings in the menu-items in a menubar in _transmission-qt_. Similar mismatch is seen in list items of a list widget as well as tabs of a tabbar widget.

__transmission-gtk__

![transmission-gtk screenshot](https://user-images.githubusercontent.com/1915507/41813019-05d03192-774b-11e8-99a9-108ae8667a93.png)

In contrast to the above image, notice the paddings in the menu-item in __transmission-qt__.

![transmission-qt screenshot](https://user-images.githubusercontent.com/1915507/41813021-0a74a25a-774b-11e8-979b-4da325b7734d.png)

**Comment by WEREWOLFGHOST** [comment]
that's right, so is my smplayer
adwaita: ![image](https://user-images.githubusercontent.com/17085541/53062944-753fda80-34fd-11e9-9a0c-960ffac3b251.png)
default: 
![screenshot_2019-02-20_10-52-41](https://user-images.githubusercontent.com/17085541/53063023-ac15f080-34fd-11e9-824a-2c877b59a2f3.png)

**Comment by MartinBriza** [comment]
Hmm, those two screenshots seem like two completely separate issues. In @jayesh-bhoot 's case it's definitely the theme and the sizes appear to be as expected from the code (still wrong, compared to upstream Adwaita, nevertheless).

However, in the case of @WEREWOLFGHOST , there is something else, that's very weird. Can you please shed some light on your environment. I'm especially interested in your Qt Platform Theme plugin, if you're on a high DPI screen and if you have changed the default font size.

**Comment by fikrillah** [comment]
@MartinBriza i have same issue as @WEREWOLFGHOST, i cant have checkbox and icon in the same column. 
I've tested it with vlc and qbittorrent. im using qt5ct on gnome with font Cantarrel 11 and Sans Serif 11.
my distro is archlinux with package source adwaita-qt5(AUR)

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/adwaita-qt/releases/tag/1.0.90.

**Comment by fikrillah** [comment]
@grulja im using vlc from flathub, and this package is installed by default. this bug still there. i tried vlc from my distro. and the problem still there...

**Comment by grulja** [comment]
> @grulja im using vlc from flathub, and this package is installed by default. this bug still there. i tried vlc from my distro. and the problem still there...

What issue do you mean, that you have one column with checkboxes and one column with icons in the menus?

**Comment by fikrillah** [comment]
yes...

**Comment by grulja** [comment]
> yes...

See bug https://github.com/FedoraQt/adwaita-qt/issues/114.
